<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Nexus.Tests" />
  </ItemGroup>

  <ItemGroup>
    <Using Remove="Microsoft.AspNetCore.Http" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="FusionPay\**\*.cs" />
    <Compile Remove="PaymentGateways\**" />
    <Content Remove="PaymentGateways\**" />
    <EmbeddedResource Remove="PaymentGateways\**" />
    <None Remove="PaymentGateways\**" />
    <PackageReference Include="Aidan.Core" Version="1.9.0" />
    <PackageReference Include="Aidan.Mongo" Version="1.5.1" />
    <PackageReference Include="Aidan.Web" Version="1.9.0" />
    <PackageReference Include="BCrypt.Net-Next" Version="4.0.3" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.13" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Operators\" />
  </ItemGroup>

</Project>
