@Nexus_HostAddress = https://websete.localhost:7254

GET {{Nexus_HostAddress}}/
Accept: application/json

###

POST {{Nexus_HostAddress}}/prototype/profit-split
Accept: application/json

###

POST {{Nexus_HostAddress}}/api/charges/pix