import type { ApiFlow } from '../types';

export const API_FLOWS: ApiFlow[] = [
  {
    id: 'auth-jwt',
    title: 'Autenticação JWT',
    description: 'Entenda como obter, armazenar e usar tokens em todas as requisições protegidas.',
    accent: 'blue',
    audience: 'Desenvolvedores integrando qualquer módulo autenticado',
    prerequisites: ['Credenciais de uma conta existente (operador ou administrador)'],
    estimatedMinutes: 10,
    outcome: 'Você conseguirá autenticar, enviar requisições protegidas e interpretar erros 401/403 corretamente.',
    steps: [
      {
        title: 'Obter tokens com sign-in',
        summary: 'Troque usuário e senha por accessToken e refreshToken.',
        narrative: 'O endpoint de sign-in valida as credenciais e retorna um par de tokens. O accessToken é de curta duração e deve acompanhar cada requisição. O refreshToken serve para renovar o acesso sem pedir senha novamente — embora o dashboard Nexus renove via sessão local, integrações externas devem implementar essa lógica.',
        why: 'Sem o accessToken válido, a API rejeita qualquer rota com [Authorize] antes mesmo de avaliar permissões de negócio.',
        outcome: 'Você recebe authenticationTokens com accessToken, refreshToken, expiresAt e tokenType "Bearer".',
        endpointId: 'auth-sign-in',
        tip: 'Armazene expiresAt e renove o token alguns minutos antes de expirar.',
        pitfalls: [
          'Não confunda 401 (token ausente/inválido) com 403 (token válido, mas sem permissão).',
          'Senhas incorretas retornam 422 com mensagem de validação, não 401.',
        ],
      },
      {
        title: 'Enviar o token em cada requisição',
        summary: 'Inclua Authorization: Bearer {accessToken} no header de todas as rotas JWT.',
        narrative: 'O Nexus não usa cookies de sessão na API REST — o contrato é stateless. Cada chamada HTTP deve carregar o JWT no header Authorization. O claim role dentro do token determina quais controllers respondem com sucesso; a verificação fina de permissão ocorre na camada de aplicação.',
        why: 'Esquecer o header resulta em 401 imediato, mesmo que o usuário esteja "logado" no seu frontend.',
        outcome: 'Requisições autenticadas passam da camada ASP.NET e chegam ao serviço de domínio.',
        endpointId: 'accounts-search',
        tip: 'No dashboard, o token é injetado automaticamente pelo apiClient — use-o como referência.',
      },
      {
        title: 'Interpretar erros de autorização',
        summary: '403 significa papel insuficiente; 422 significa regra de negócio violada.',
        narrative: 'Quando o token é válido mas o papel não permite a ação — por exemplo, um operador tentando criar operação — a API retorna 403. Já validações como campos obrigatórios ou entidades inexistentes retornam 422 com mensagem descritiva. Essa distinção é crítica para UX de integração: 403 pede elevação de permissão; 422 pede correção de payload.',
        why: 'Tratar ambos como "erro genérico" dificulta suporte e logs.',
        outcome: 'Você consegue direcionar o usuário final para a ação correta conforme o status HTTP.',
        endpointId: 'ops-create',
        pitfalls: [
          'Operadores não acessam rotas /administrator — use as rotas do papel correto.',
          'O claim role está no JWT decodificável; inspecione-o durante desenvolvimento.',
        ],
      },
    ],
  },
  {
    id: 'onboarding',
    title: 'Onboarding do sistema',
    description: 'Provisione o primeiro administrador e prepare contas para operadores.',
    accent: 'violet',
    audience: 'Equipe de implantação / DevOps na primeira instalação',
    prerequisites: ['Token mestre configurado em Authentication:AdministratorToken no servidor'],
    estimatedMinutes: 15,
    outcome: 'O ambiente terá um administrador ativo e operadores prontos para receber atribuições em operações.',
    steps: [
      {
        title: 'Criar o administrador inicial',
        summary: 'Primeiro cadastro exige token mestre no header Authorization (não Bearer).',
        narrative: 'Em instalações novas, não existe administrador para aprovar outros cadastros. O servidor aceita um único endpoint de bootstrap: sign-up/administrator. O header Authorization deve conter exatamente o valor de Authentication:AdministratorToken da configuração — sem prefixo "Bearer". Após sucesso, o próprio response já traz tokens JWT para o novo admin.',
        why: 'Evita que qualquer pessoa na internet crie contas administrativas em ambientes expostos.',
        outcome: 'Conta administradora criada com tokens JWT válidos para gestão completa.',
        endpointId: 'auth-sign-up-admin',
        pitfalls: [
          'Usar Bearer no token mestre causa 401.',
          'Este passo só é necessário uma vez por ambiente (ou quando resetar credenciais).',
        ],
      },
      {
        title: 'Registrar operadores',
        summary: 'Operadores se cadastram via sign-up público ou admin cria contas.',
        narrative: 'Existem dois caminhos: o operador se registra em sign-up/operator (público) ou o administrador cria a conta via POST /api/accounts/administrator e depois concede o papel Operator. O primeiro caminho é mais rápido para equipes que já têm credenciais; o segundo dá controle total ao admin sobre usernames.',
        why: 'Operadores são quem gera cobranças e visualiza pagamentos no dia a dia.',
        outcome: 'Contas com papel Operator existentes e capazes de autenticar.',
        endpointId: 'auth-sign-up-operator',
        tip: 'Após criar a conta, o operador ainda precisa ser atribuído a uma equipe para ver operações.',
      },
      {
        title: 'Ajustar papéis e permissões',
        summary: 'Conceda papéis adicionais ou permissões granulares conforme a hierarquia.',
        narrative: 'O Nexus separa papel (role) de permissão (permission). Papéis definem o painel e rotas base; permissões refinam ações dentro do papel. Use grant/revoke em roles para elevar um operador a team-leader ou operation-administrator, e permissions para casos específicos documentados no módulo de contas.',
        why: 'A estrutura organizacional real raramente é binária admin/operador.',
        outcome: 'Cada conta com o conjunto correto de papéis para sua função.',
        endpointId: 'accounts-grant-role',
      },
    ],
  },
  {
    id: 'operations-setup',
    title: 'Configurar operação e equipe',
    description: 'Monte a hierarquia operação → equipe → operadores antes de transacionar.',
    accent: 'green',
    audience: 'Administradores configurando a estrutura comercial',
    prerequisites: ['Conta administradora autenticada', 'Pelo menos um operador cadastrado'],
    estimatedMinutes: 20,
    outcome: 'Operadores enxergam suas operações no painel e cobranças podem ser vinculadas corretamente.',
    steps: [
      {
        title: 'Criar a operação',
        summary: 'A operação é o container raiz de equipes, gateways e pagamentos.',
        narrative: 'Pense na operação como uma "empresa" ou "linha de negócio" dentro do Nexus. Toda cobrança PIX referencia um operationId. Ao criar, defina nome e descrição — campos usados na UI e em relatórios. Uma instalação pode ter dezenas de operações isoladas.',
        why: 'Sem operação, não há contexto para equipes, gateways ou cobranças.',
        outcome: 'operationId retornado e persistido para os próximos passos.',
        endpointId: 'ops-create',
      },
      {
        title: 'Criar equipes dentro da operação',
        summary: 'Equipes organizam operadores e regras de gateway por subdivisão.',
        narrative: 'Dentro de cada operação, equipes segmentam operadores — por região, produto ou turno. Cada equipe pode ter estratégia de gateway própria e laranjas atribuídos. O administrador cria a equipe informando operationId e nome.',
        why: 'Operadores nunca veem a operação inteira — apenas equipes às quais foram atribuídos.',
        outcome: 'teamId disponível para atribuições de operadores.',
        endpointId: 'ops-create-team',
      },
      {
        title: 'Atribuir operadores às equipes',
        summary: 'Vincule operatorId à dupla operationId + teamId.',
        narrative: 'A atribuição é o elo entre pessoa e estrutura. Um operador pode pertencer a múltiplas equipes da mesma operação. Após atribuir, o operador passa a listar a operação em POST /api/operations/operator/search e pode gerar cobranças com seu operatorId.',
        why: 'Cobranças sem operador atribuído geram inconsistência em comissões e relatórios.',
        outcome: 'Operador vinculado e visível na operação.',
        endpointId: 'ops-assign-operator',
        tip: 'Use search de operadores para atribuir se não souber o ID de memória.',
      },
      {
        title: 'Validar a visão do operador',
        summary: 'Confirme que o operador autenticado enxerga apenas o que deve.',
        narrative: 'Faça sign-in como operador e chame a busca de operações do painel operador. A lista deve conter somente operações com equipes atribuídas. Se vazia, revise atribuições — é o erro mais comum pós-onboarding.',
        why: 'Validação end-to-end evita tickets de "não vejo minha operação".',
        outcome: 'Lista de operações coerente com as atribuições feitas.',
        endpointId: 'ops-operator-search',
        pitfalls: ['Operador sem equipe = lista vazia, não é bug da API.'],
      },
    ],
  },
  {
    id: 'payments-pix',
    title: 'Cobrança e acompanhamento PIX',
    description: 'Do QR Code ao status pago, incluindo tempo real via SignalR.',
    accent: 'amber',
    audience: 'Integradores de checkout e backends de pagamento',
    prerequisites: ['Operação configurada', 'Gateway com credenciais ativas', 'operatorId válido (opcional na cobrança pública)'],
    estimatedMinutes: 25,
    outcome: 'Fluxo completo de cobrança com acompanhamento em tempo real e ações administrativas.',
    steps: [
      {
        title: 'Gerar a cobrança PIX',
        summary: 'POST com operationId, amount e opcionalmente operatorId.',
        narrative: 'A cobrança pública em /api/charges/pix não exige JWT — ideal para checkout em sites de terceiros. O response traz id (paymentId), pixCode (copia-e-cola ou base para QR), paymentRecipient e expirationTimeSeconds. Guarde o id imediatamente: ele alimenta SignalR e consultas posteriores.',
        why: 'Este é o momento em que o pagamento entra no sistema e o gateway é acionado.',
        outcome: 'PIX gerado e pronto para exibição ao pagador.',
        endpointId: 'charges-pix-public',
        tip: 'Exiba o QR com biblioteca padrão BR Code a partir do pixCode retornado.',
        pitfalls: [
          'operationId inválido retorna 422.',
          'Sem gateway configurado na operação, a cobrança falha na orquestração interna.',
        ],
      },
      {
        title: 'Inscrever-se no hub SignalR',
        summary: 'Conecte em /hubs/payment-status e chame JoinPaymentAsync(paymentId).',
        narrative: 'Polling HTTP funciona, mas o Nexus oferece push via SignalR. Após conectar, invoque JoinPaymentAsync passando o paymentId da cobrança. O servidor adiciona sua conexão ao grupo payment:{id}. Quando o gateway confirma pagamento via webhook, todos no grupo recebem PaymentStatusChangedNotification.',
        why: 'Tempo real melhora UX de checkout — o cliente vê "pago" instantaneamente.',
        outcome: 'Conexão inscrita e pronta para receber eventos de status.',
        endpointId: 'signalr-hub',
        tip: 'Sempre chame LeavePaymentAsync ao sair da tela de pagamento.',
      },
      {
        title: 'Consultar detalhe administrativo',
        summary: 'Administradores podem auditar qualquer pagamento a qualquer momento.',
        narrative: 'A rota GET /api/payments/administrator/{paymentId} retorna estado completo: valor, status, operador vinculado, timestamps e metadados do gateway. Use para suporte, reconciliação e dashboards internos. Operadores têm rota equivalente limitada aos próprios pagamentos.',
        why: 'SignalR notifica mudanças; HTTP detalha o estado atual com contexto completo.',
        outcome: 'Visão auditável do pagamento para backoffice.',
        endpointId: 'payments-detail',
      },
      {
        title: 'Ações manuais: confirmar ou estornar',
        summary: 'Admins podem forçar pay ou refund quando o gateway não refletiu corretamente.',
        narrative: 'Em cenários de conciliação manual, POST .../pay marca como pago sem esperar webhook. POST .../refund inicia estorno de pagamentos confirmados. Essas ações são destrutivas — restrinja a administradores e registre em logs internos. O kill e bind-operator são ações adicionais documentadas na referência de pagamentos.',
        why: 'Operação real exige override humano em edge cases de gateway.',
        outcome: 'Status do pagamento alinhado com a realidade financeira.',
        endpointId: 'payments-pay',
        pitfalls: ['Estornar pagamento pendente falha — apenas pagos podem ser estornados.'],
      },
    ],
  },
  {
    id: 'scripts-lifecycle',
    title: 'Ciclo de vida de scripts',
    description: 'Inventário, releases semânticas, canais e resolução em produção.',
    accent: 'rose',
    audience: 'Engenheiros de plataforma e admin de scripts',
    prerequisites: ['Conta administradora', 'Código JavaScript do script pronto para publicar'],
    estimatedMinutes: 30,
    outcome: 'Script resolvível em produção por host com versionamento e cache ETag.',
    steps: [
      {
        title: 'Registrar o script no inventário',
        summary: 'Defina nome, hostPatterns e descrição.',
        narrative: 'O inventário é o catálogo administrativo. hostPatterns determinam como o script é encontrado em runtime — use curingas como *.dominio.com. Scripts sem hostPatterns resolvem apenas por name. A prioridade desempata quando múltiplos scripts casam o mesmo host.',
        why: 'Sem registro, não há onde publicar releases.',
        outcome: 'scriptId criado e visível no Script Studio do dashboard.',
        endpointId: 'scripts-create',
      },
      {
        title: 'Publicar uma release',
        summary: 'Envie sourceCode; versão é automática ou via major/minor/patch.',
        narrative: 'Cada publicação cria um artefato imutável com hash do código. Informe sourceCode no body; opcionalmente major, minor, patch para versão semântica explícita — omita para incremento automático do patch. Releases depreciadas não resolvem em produção a menos que allowDeprecated=true.',
        why: 'Versionamento imutável permite rollback por promoção de canal.',
        outcome: 'releaseId e version retornados.',
        endpointId: 'scripts-publish-release',
        tip: 'Teste em canal beta antes de promover para prod.',
      },
      {
        title: 'Promover release para canal',
        summary: 'Associe releaseId ao canal (prod, beta ou custom).',
        narrative: 'Canais são ponteiros: prod aponta para a release que clientes recebem em produção. A promoção é atômica — muda o ponteiro sem alterar o código da release. Canais customizados são criados via POST .../channels com customName.',
        why: 'Separa "o que foi publicado" de "o que está em produção".',
        outcome: 'Canal prod servindo a nova versão.',
        endpointId: 'scripts-promote-channel',
      },
      {
        title: 'Resolver em runtime (cliente)',
        summary: 'GET /scripts?host=&name=&channel= com suporte a ETag.',
        narrative: 'Browsers e extensões chamam a rota pública sem auth. Envie If-None-Match com ETag anterior para receber 304 quando nada mudou — essencial para performance. O response contém sourceCode pronto para injeção. Resolução considera host, nome, canal e opcionalmente versão fixa.',
        why: 'Este é o endpoint que seus usuários finais efetivamente consomem.',
        outcome: 'Script entregue ao cliente com cache eficiente.',
        endpointId: 'scripts-resolve',
        pitfalls: [
          'Host que não casa com hostPatterns não resolve o script.',
          'Canal sem promoção retorna vazio ou versão antiga.',
        ],
      },
    ],
  },
  {
    id: 'gateways-setup',
    title: 'Configurar gateway de pagamento',
    description: 'Credenciais PIX para Frendz, Wintech ou SigiloPay.',
    accent: 'blue',
    audience: 'Administradores de integração financeira',
    prerequisites: ['Chaves de API do provedor escolhido', 'Operação existente para vincular credenciais'],
    estimatedMinutes: 15,
    outcome: 'Gateway ativo e capaz de processar cobranças PIX da operação.',
    steps: [
      {
        title: 'Auditar credenciais existentes',
        summary: 'Liste credenciais do provedor antes de criar duplicatas.',
        narrative: 'Cada provedor (frendz, wintech, sigilopay) tem coleção própria de credenciais. A busca retorna label, enabled e id. Credenciais desabilitadas não participam do roteamento. Verifique se já existe conta principal antes de adicionar outra.',
        why: 'Duplicar credenciais ativas pode causar roteamento ambíguo.',
        outcome: 'Inventário claro do que já está configurado.',
        endpointId: 'gateways-search',
        tip: 'O path param {provider} é literal: frendz, wintech ou sigilopay.',
      },
      {
        title: 'Cadastrar novas credenciais',
        summary: 'Body varia por provedor — consulte a referência do gateway.',
        narrative: 'Frendz usa apiKey; Wintech e SigiloPay usam pares de chaves pública/secreta. O label é livre para identificação humana. Comece com enabled: true apenas após validar em sandbox. Credenciais são vinculadas a operações/equipes em passos separados na gestão de operações.',
        why: 'Sem credencial ativa, cobranças PIX não alcançam o provedor.',
        outcome: 'Credencial persistida e disponível para atribuição.',
        endpointId: 'gateways-add-credentials',
        pitfalls: ['Chave inválida só falha na primeira cobrança real — teste com valor simbólico.'],
      },
      {
        title: 'Validar com cobrança de teste',
        summary: 'Gere PIX administrativo e confirme retorno do provedor.',
        narrative: 'Com credenciais e operação vinculadas, use POST /api/charges/administrator/pix com valor mínimo. Acompanhe via SignalR ou consulta de pagamento. Sucesso confirma que a cadeia operação → gateway → provedor está íntegra.',
        why: 'Teste ponta a ponta é a única prova de configuração correta.',
        outcome: 'Primeira cobrança processada pelo gateway configurado.',
        endpointId: 'charges-pix-admin',
      },
    ],
  },
];

export const flowById = new Map(API_FLOWS.map((f) => [f.id, f]));
